### ISSUE TITLE
HTML validation errors

### ISSUE THREAD

**Issue by Magew** [Birssan/grav-theme-nucleare#1]
Hi,

There are a few html validation problems with this theme that are simple fixes. However, the one thing I cannot fix is a stray <code>script</code> tag in the footer. What file do I need to edit to fix whatever "{{ assets.js('bottom') }}" is? And where is it?

It has two <code>script</code> tags and only needs one. 

Other errors that I've fixed are simple and I suggest you look into them for your next release/update to this theme.

Thanks

**Comment by Magew** [comment]
I found it in <code>/nucleare/templates/partials/simplesearch_searchbox.html.twig</code>.

The closing <code>style</code> tag in that file is redundant. When you call on the JS assets, it automatically adds your <code>style</code> tags, both opening and closing. I assume you probably knew that and just added it by accident.

You've also got a couple role attributes that are redundant. Like using the role attribute with <code>nav</code>.

And for some reason, w3 will not validate the search role when used on a form, so you need to use it on the above container.

The last error I am left with is <code>The aria-controls attribute must point to an element in the same document.</code> and I have no idea what it means and what to do at this moment.

**Comment by seb-vial** [comment]
Hello,
Thanks for reporting this.
For the extra script tag, I just forgot I guess, I copied the template from the simplesearch plugin, and then changed it. It was including a script tag just below the HTML content, so there was a script tag in the middle of the DOM, I changed that by adding it at the end of the body (that's why there's a `assets.js('bottom')`) and removing the script tags, I gues I forgot to removing the closing one ^^

Concerning aria attributs and roles, I didn't change anything from the original theme developed for Wordpress. I didn't think to check them.

Could you please make a pull request of what you've changed so far regarding this issue please ?

**Comment by Magew** [comment]
Makes sense! No worries. I have no idea what aria is, but I removed the aria-controls attribute and everything works so I guess it isn't needed. I'm sure there is probably some more cleaning to do, but as far as validation goes, its good to go now with my edits.

I'm new to using Github, so I assume a pull request sends you my changes? I'll give it a go.

**Comment by seb-vial** [comment]
Well aria attributs are actually used for accessibility, people who are disabled (like blind for example). They have special devices which read all kind of attributs we don't usually need for ourselves.

About pull request, you can simply fork my repo, make changes and a pull a request here request with your committed changes

**Comment by Magew** [comment]
I see. Well, it seems it was missing something that was essential to its purpose, so I removed it for now. I'll look into validating the theme for accessibility use and making sure everything is good for that.

**Comment by seb-vial** [comment]
Ok, it should be good now. I still need to do some testing and I'll release a new version
